version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "10080:80/tcp"
    #  - "10443:443/tcp"
    #mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.0.6
    environment:
      TZ: America/Toronto
      WEBPASSWORD: VqdYdmNBh73ED2NKyVGJkiKJjr6mtWmBNGh99Qd2
      ServerIP: 192.168.0.209
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=pihole.awiebe.online
      - TZ=America/Toronto
      - WEBPASSWORD=VqdYdmNBh73ED2NKyVGJkiKJjr6mtWmBNGh99Qd2
      - ServerIP=192.168.0.6
    #extra_hosts:
    #  - "RokuTV:192.168.0.10"
    #  - "BedroomPI:172.27.0.1"
networks:
  pihole_network:                         # Name of network
    driver: macvlan                       # Use the macvlan network driver
    driver_opts:
      parent: ens192                    # If open vSwitch is disabled use eth0 (or eth1 +)
    ipam:
      config:
        - subnet: 192.168.0.0/24        # Specify subnet
          gateway: 192.168.0.1          # Gateway address
