version: '3'

services:
  reverse:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    #  - ./config:/etc/nginx:ro
    #  - ./certs:/etc/ssl/private:ro
      - ./conf.d:/etc/nginx/conf.d
