version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: env.env
    #environment:
    #  MYSQL_ROOT_PASSWORD: in env file
    volumes:
      - ./datadir:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 7676:8080

  clarkson:
    image: linuxserver/clarkson
    container_name: clarkson
    env_file: envapp.env
    #environment:    
    #  - PUID=500
    #  - PGID=500
    #  - MYSQL_HOST=db
    #  - MYSQL_USERNAME=clarkson
    #  - MYSQL_PASSWORD=
    #  - ENABLE_REGISTRATIONS=true/false
    #  - TZ=Europe/London
    ports:
      - 9999:3000
    restart: unless-stopped
